package todoly.enums;

public enum Context {
	MAIN_MENUE,
	LIST_TASKS_MENU,
	ORDER_BY_DUE_DATE,
	LIST_PROJECTS_MENU,
	FILTER_BY_PROJECT,
	NEW_TASK,
	EDIT_TASK_MENU,
	UPDATE_TASK,
	MARK_TASK_AS_DONE,
	REMOVE_TASK,
	SAVE_AND_QUIT
}
