package todoly.util.enums;

public enum MenuOption {
	MAIN_MENUE,
		LIST_TASKS_MENU,
			LIST_TASKS_BY_DUE_DATE,
			LIST_TASKS_FILTERED_BY_PROJECT,
		ADD_NEW_TASK,
		EDIT_TASK_MENU,
			UPDATE_TASK_STATUS,
			UPDATE_TASK_TITLE,
			UPDATE_TASK_DUE_DATE,
			UPDATE_TASK_PROJECT,
			REMOVE_TASK,
		SAVE_AND_QUIT;
}
